name: CI on shorthand_datetime
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Test on multiple Python versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install '.[dev, test]'  # Ensure that test dependencies are installed

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files

    - name: Run tests with pytest and collect coverage
      run: |
        pytest --cov=.  # Collect coverage during test execution

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    # - name: Publish coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: coverage.xml
    #     flags: unittests
    #     fail_ci_if_error: true
